name: Build-Push-Deploy-3Tier

on:
  push:
    branches: [ "main" ]

env:
  NGINX: ${{ github.ref_name }}-nginx:latest
  WEB_IMAGE: ${{ github.ref_name }}-web:latest
  
jobs:
  build-push-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ---------- Build & Push Frontend ----------
      - name: Build Nginx
        run: docker build -t $NGINX ./3tire-app/nginx

      - name: Push Nginx
        run: docker push $NGINX

      - name: Tag Docker Image
        run: |
          docker tag $NGINX:latest ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:latest
 
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:latest

      # ---------- Build & Push Backend ----------
      - name: Build Web
        run: docker build -t $WEB ./3tire-app/web

      - name: Push Web
        run: docker push $WEB

      # ---------- Deploy to Server ----------
      - name: Copy docker-compose to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.TARGET_SERVER }}
          username: ${{ secrets.TARGET_SSH_USER }}
          key: ${{ secrets.TARGET_SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "docker-compose.prod.yml"
          target: "~/docker/3tier-app/"

      - name: Run Deployment
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.TARGET_SERVER }}
          username: ${{ secrets.TARGET_SSH_USER }}
          key: ${{ secrets.TARGET_SSH_KEY }}
          script: |
            cd ~/3tier-app
            export POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d --remove-orphans
            docker image prune -f
