name: Build-Push-Deploy-3Tier

on:
  push:
    branches: [ "main" ]

env:
  FRONTEND_IMAGE: ${{ github.ref_name }}-frontend:latest
  BACKEND_IMAGE: ${{ github.ref_name }}-backend:latest

jobs:
  build-push-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ---------- Build & Push Frontend ----------
      - name: Build Frontend
        run: docker build -t $FRONTEND_IMAGE ./3tire-app/frontend

      - name: Push Frontend
        run: docker push $FRONTEND_IMAGE

      # ---------- Build & Push Backend ----------
      - name: Build Backend
        run: docker build -t $BACKEND_IMAGE ./3tire-app/backend

      - name: Push Backend
        run: docker push $BACKEND_IMAGE

      # ---------- Deploy to Server ----------
      - name: Copy docker-compose to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.TARGET_SERVER }}
          username: ${{ secrets.TARGET_SSH_USER }}
          key: ${{ secrets.TARGET_SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "docker-compose.prod.yml"
          target: "~/docker/3tier-app/"

      - name: Run Deployment
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.TARGET_SERVER }}
          username: ${{ secrets.TARGET_SSH_USER }}
          key: ${{ secrets.TARGET_SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/3tier-app
            export POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d --remove-orphans
            docker image prune -f
